/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package1;

/**
 *
 * @author SOHAM BABSHETYE
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booksuggestions = new javax.swing.JButton();
        addbook = new javax.swing.JButton();
        addstudent = new javax.swing.JButton();
        issuebook = new javax.swing.JButton();
        returnbook = new javax.swing.JButton();
        latereturn = new javax.swing.JButton();
        statistics = new javax.swing.JButton();
        close = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booksuggestions.setBackground(new java.awt.Color(208, 188, 118));
        booksuggestions.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        booksuggestions.setForeground(new java.awt.Color(0, 0, 0));
        booksuggestions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/book suggestion icon.png"))); // NOI18N
        booksuggestions.setText("Book Suggestions");
        booksuggestions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        booksuggestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksuggestionsActionPerformed(evt);
            }
        });
        getContentPane().add(booksuggestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 120, 60));

        addbook.setBackground(new java.awt.Color(208, 188, 118));
        addbook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addbook.setForeground(new java.awt.Color(0, 0, 0));
        addbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/book.png"))); // NOI18N
        addbook.setText("Add Book");
        addbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });
        getContentPane().add(addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 60));

        addstudent.setBackground(new java.awt.Color(208, 188, 118));
        addstudent.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addstudent.setForeground(new java.awt.Color(0, 0, 0));
        addstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/add-student.png"))); // NOI18N
        addstudent.setText("Add Student");
        addstudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentActionPerformed(evt);
            }
        });
        getContentPane().add(addstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 120, 60));

        issuebook.setBackground(new java.awt.Color(208, 188, 118));
        issuebook.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        issuebook.setForeground(new java.awt.Color(0, 0, 0));
        issuebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/Bookissue.jpeg"))); // NOI18N
        issuebook.setText("Issue Book");
        issuebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        issuebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebookActionPerformed(evt);
            }
        });
        getContentPane().add(issuebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 120, 60));

        returnbook.setBackground(new java.awt.Color(208, 188, 118));
        returnbook.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        returnbook.setForeground(new java.awt.Color(0, 0, 0));
        returnbook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/return.png"))); // NOI18N
        returnbook.setText("Return Book");
        returnbook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        returnbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookActionPerformed(evt);
            }
        });
        getContentPane().add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 120, 60));

        latereturn.setBackground(new java.awt.Color(208, 188, 118));
        latereturn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        latereturn.setForeground(new java.awt.Color(0, 0, 0));
        latereturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/late return_1.png"))); // NOI18N
        latereturn.setText("Late Return");
        latereturn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        latereturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latereturnActionPerformed(evt);
            }
        });
        getContentPane().add(latereturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 120, 60));

        statistics.setBackground(new java.awt.Color(208, 188, 118));
        statistics.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        statistics.setForeground(new java.awt.Color(0, 0, 0));
        statistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/statistics.png"))); // NOI18N
        statistics.setText("Statistics");
        statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsActionPerformed(evt);
            }
        });
        getContentPane().add(statistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 120, 40));

        close.setBackground(new java.awt.Color(208, 188, 118));
        close.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        close.setForeground(new java.awt.Color(0, 0, 0));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/close.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 120, 40));

        back.setBackground(new java.awt.Color(208, 188, 118));
        back.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/340.png"))); // NOI18N
        back.setText("Back");
        back.setToolTipText("");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 120, 40));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(208, 188, 118));
        jLabel1.setText("Home Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GiphyImages/BOOKTRAKER2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void issuebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebookActionPerformed
        // TODO add your handling code here:
        BookIssue bi=new BookIssue();
        bi.setVisible(true);
        
        
    }//GEN-LAST:event_issuebookActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        LoginPage lp=new LoginPage();
        lp.setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void addstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentActionPerformed
        // TODO add your handling code here:
        ReaderInfo ri =new ReaderInfo();
        ri.setVisible(true);
        
        
    }//GEN-LAST:event_addstudentActionPerformed

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookActionPerformed
        // TODO add your handling code here:
        Bookinform bm=new Bookinform();
        bm.setVisible(true);
        
        
        
    }//GEN-LAST:event_addbookActionPerformed

    private void returnbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookActionPerformed
          BookReturn br=new BookReturn();
           br.setVisible(true);
          
    }//GEN-LAST:event_returnbookActionPerformed

    private void latereturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latereturnActionPerformed
        // TODO add your handling code here:
        LateReturn lr=new LateReturn();
        lr.setVisible(true);
        
    }//GEN-LAST:event_latereturnActionPerformed

    private void booksuggestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksuggestionsActionPerformed
        // TODO add your handling code here:
        BookSuggestions bs =new BookSuggestions();
        bs.setVisible(true);
        
        
    }//GEN-LAST:event_booksuggestionsActionPerformed

    private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsActionPerformed
        // TODO add your handling code here:
        Statistics s=new Statistics();
        s.setVisible(true);
        
    }//GEN-LAST:event_statisticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbook;
    private javax.swing.JButton addstudent;
    private javax.swing.JButton back;
    private javax.swing.JButton booksuggestions;
    private javax.swing.JButton close;
    private javax.swing.JButton issuebook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton latereturn;
    private javax.swing.JButton returnbook;
    private javax.swing.JButton statistics;
    // End of variables declaration//GEN-END:variables
}
